project:
  type: website
  output-dir: docs
  
website:
  title: "SEGUID"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/seguid/seguid.org/
        aria-label: GitHub      
  search: 
    location: navbar
    type: overlay
  repo-url: https://github.com/seguid/seguid.org/
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  


