project:
  type: website
  output-dir: docs
  
website:
  title: "SEGUID"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Available Software
        menu:
          - text: <strong>seguid</strong> (Python package)
            url:  https://github.com/seguid/seguid-python/
          - text: <strong>seguid</strong> (R package)
            url:  https://seguid-r.seguid.org
      - quality.qmd
      - publications.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/seguid/seguid.org/
        aria-label: GitHub
        
  search: 
    location: navbar
    type: overlay
    
  repo-url: https://github.com/seguid/seguid.org/
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  


